export const data = {
  "daily_index": 1,
  "yearly_index": 1,
  "monthly_index": 1,
  "random_MVSG_2_energy": 1410,
  "random_MVSG_3_energy": 1444,
  "chiller3_status": 0,
  "chiller4_status": 0,
  "chiller1_supply_temp": 15,
  "chiller2_supply_temp": 6,
  "chiller3_supply_temp": 21,
  "chiller4_supply_temp": 6,
  "chiller1_return_temp": 14,
  "chiller2_return_temp": 5,
  "chiller3_return_temp": 14,
  "chiller4_return_temp": 9,
  "chiller1_op_hours": 1,
  "chiller2_op_hours": 17,
  "chiller3_op_hours": 13,
  "chiller4_op_hours": 23,
  "chillers_op_hours": 54,
  "monthlyenergy_chiller1": 876,
  "monthlyenergy_chiller2": 953,
  "monthlyenergy_chiller3": 905,
  "monthlyenergy_chiller4": 890,
  "in_Patients": 17,
  "out_Patients": 59,
  "chiller1_maintenance_hours": 10,
  "chiller2_maintenance_hours": 17,
  "chiller3_maintenance_hours": 13,
  "chiller4_maintenance_hours": 23,
  "main_supply_temp": 8,
  "main_return_temp": 12,
  "gen1_status": 0,
  "gen2_status": 0,
  "gen1_engine_runtime": 65,
  "gen2_engine_runtime": 57,
  "gen1_solar": 7147,
  "gen2_solar": 3015,
  "gen1_last_op": "7/3/2024",
  "gen2_last_op": "6/18/2024",
  "gen1_bv": 0,
  "index": 1,
  "gen2_bv": 1,
  "gen1_volt": 372,
  "gen2_volt": 374,
  "gen1_curr": 3,
  "gen2_curr": 5,
  "gen2_energy": 496,
  "gen1_object_feed1": 179,
  "gen2_object_feed1": 260,
  "gen1_object_feed2": 216,
  "gen2_object_feed2": 114,
  "gen1_object_feed3": 94,
  "gen2_object_feed3": 170,
  "gen1_energy": 369,
  "dailyenergy_MVSG_incoming2_energy": 2103,
  "dailyenergy_MVSG_incoming3_energy": 2053,
  "dailyenergy_MVSG": 4156,
  "monthlyenergy_MVSG": 7113,
  "gen1_estimated_feed_time": 489,
  "gen2_estimated_feed_time": 544,
  "dailycost_sg": 6649.6,
  "monthlycost_sg": 11380.8,
  "yearlyenergy_MVSG": 7113,
  "yearlycost_sg": 11380.8,
  "monthlycost_g": 21192.43,
  "monthlycost_f": 17115.91,
  "monthlycost_s": 20210.33,
  "monthlycost_th": 33253.242000000006,
  "monthlycost_roof": 7568,
  "monthlycost_Hospital": 142284,
  "monthlycost_clinic": 85370.4,
  "monthlycost_Utilities": 34148.16,
  "daily_water_consumption": 14,
  "daily_water_cost": 38.5,
  "monthly_water_consumption": 984,
  "yearly_water_consumption": 7680,
  "daily_oxygen_consumption": 3278,
  "daily_oxygen_cost": 4261.400000000001,
  "monthly_oxygen_consumption": 220282,
  "monthly_oxygen_cost": 196768.1,
  "yearly_oxygen_consumption": 332560,
  "yearly_oxygen_cost": 405366.1,
  "dailyenergy_Hospital": 7559,
  "dailyenergy_Clinics": 5268,
  "dailyenergy_Utilities": 5658,
  "dailyenergy_ele": 1731,
  "dailyenergy_chillers": 2499,
  "dailyenergy_AHU": 1873,
  "dailyenergy_Boilers": 2383,
  "monthlyenergy_Hospital": 9905,
  "monthlyenergy_Clinics": 4621,
  "monthlyenergy_Utilities": 8109,
  "monthlyenergy_ele": 4001,
  "monthlyenergy_chillers": 4681,
  "monthlyenergy_Boilers": 4827,
  "Inpatient_Beds_used": 9,
  "Inpatient_Beds_unused": 252,
  "ICU_CCU_Beds_used": 1,
  "ICU_CCU_Beds_unused": 108,
  "Emergency_Beds_used": 42,
  "Emergency_Beds_unused": 20,
  "Incubators_Beds_used": 3,
  "Incubators_Beds_unused": 51,
  "Total_Hospital_Beds_used": 19,
  "Total_Hospital_Beds_unused": 431,
  "beds_Occupancy_Rate": 0,
  "Hospital_Occupancy_Rate": 53,
  "Clinic_Occupancy_Rate": 72,
  "Mask_Policy_Violations": 1,
  "NuOF_Detected_Falls": 1,
  "transformer_on": 12,
  "transformer_off": 0,
  "generator_on": 4,
  "generator_off": 2,
  "Elevator_on": 13,
  "Elevator_off": 7,
  "monthly_water_cost": 43.4,
  "monthly_total_cost": 208192.3,
  "HVAC_alarm": 0,
  "medical_gas_alarm": 0,
  "fire_fighting_alarm": 0,
  "transformer_alarm": 0,
  "elevator_alarm": 0,
  "F_AHU_ON": 45,
  "F_AHU_OFF": 24,
  "chiller_on": 0,
  "chiller_off": 4,
  "vaccum_press": -6.6,
  "air_4bar_press": 5,
  "air_7bar_press": 6.1,
  "oxygen_press": 4.9,
  "updated_at": "4/1/2024 01:00 AM",
  "chiller1_status": 1,
  "chiller2_status": 1,
  "air_4bar_percentage": 74.3,
  "air_7bar_percentage": 70.9,
  "vaccum_percentage": 81.1,
  "oxygen_percentage": 81.3,
  "no_of_surgry_month": 75,
  "no_of_dialysis_month": 84,
  "no_of_x-rays_month": 79,
  "Inpatient_Beds_used_monthly": 84,
  "Inpatient_Beds_unused_monthly": 80,
  "ICU_CCU_Beds_used_monthly": 80,
  "ICU_CCU_Beds_unused_monthly": 80,
  "Emergency_Beds_used_monthly": 84,
  "Emergency_Beds_unused_monthly": 80,
  "Incubators_Beds_unused_monthly": 84,
  "Incubators_Beds_used_monthly": 87,
  "no_of_pepole_cam1": 75,
  "no_of_pepole_cam2": 80,
  "no_of_pepole_cam3": 79,
  "no_of_pepole_cam4": 72,
  "daily_carbon_foot_print": 88,
  "monthly_carbon_foot_print": 89,
  "yearly_water_cost": 5879,
  "Chiller1_performance": 1,
  "Chiller2_performance": 2,
  "Chiller3_performance": 0,
  "Chiller4_performance": 0,
  "surgeries": 60,
  "dialysis": 5,
  "blood_bank": 18,
  "medical_lab": 50,
  "xray_operation": 20,
  "temp_outside": 27,
  "temp_inside": 21,
  "chiller1_op_rate": 30,
  "chiller2_op_rate": 8,
  "chiller3_op_rate": 14,
  "chiller4_op_rate": 20,
  "chiller1_maintenance_hours_percentage": 72,
  "chiller2_maintenance_hours_percentage": 66,
  "chiller3_maintenance_hours_percentage": 63,
  "chiller4_maintenance_hours_percentage": 12,
  "Inpatient_Beds": 58,
  "Emergency_Beds": 26,
  "ICU_CCU_Beds": 109,
  "Total_Hospital_Beds": 427,
  "Incubators_Beds": 54,
  "vaccum_press_percent": 56,
  "air_4bar_press_percent": 38,
  "oxygen_press_percent": 58,
  "chiller2_maintenance_days": 11,
  "chiller1_maintenance_days": 11,
  "chiller3_maintenance_days": 12,
  "chiller4_maintenance_days": 8,
  "energy_dental_xray": 33040,
  "cost_dental_xray": 49427,
  "energy_radiology_lab": 35765,
  "cost_radiology_lab": 32293,
  "energy_bio_tanks": 33793,
  "cost_bio_tanks": 40568,
  "energy_triage": 29222,
  "cost_triage": 44357,
  "energy_dental_lab": 37593,
  "cost_dental_lab": 49457,
  "energy_surgical_care": 34684,
  "cost_surgical_care": 48365,
  "energy_icu": 49736,
  "cost_icu": 32258,
  "energy_critical_care": 46496,
  "cost_critical_care": 45990,
  "energy_blood_banks": 42359,
  "cost_blood_banks": 36713,
  "energy_pharmacy": 41045,
  "cost_pharmacy": 31840,
  "energy_medical_lab": 48763,
  "cost_medical_lab": 36374,
  "energy_pediatric_care": 38577,
  "cost_pediatric_care": 32923,
  "energy_emergency_care": 36412,
  "cost_emergency_care": 35925,
  "energy_maternity": 37823,
  "cost_maternity": 43869,
  "energy_operation_theater": 47560,
  "cost_operation_theater": 45665,
  "energy_lab": 46435,
  "cost_lab": 31673,
  "carbon_foot_print_GF": 20,
  "carbon_foot_print_1F": 30,
  "carbon_foot_print_2F": 35,
  "carbon_foot_print_3F": 15,
  "monthlyenergy_g": 13163,
  "monthlyenergy_f": 10631,
  "monthlyenergy_s": 12553,
  "monthlyenergy_th": 20603,
  "Total_Hospital_Beds_used_monthly": 260,
  "Total_Hospital_Beds_unused_monthly": 167,
  "Hospital_Boiler_1_Status": 1,            
  "Hospital_Boiler_1_Alarm": 0,         
  "Hospital_Boiler_1_Hot_Water_Volume": 1365,
  "Hospital_Boiler_1_Hot_Water_Temperature": 86,
  "Hospital_Boiler_1_BC_Sequence_Time": 46579,
  "Hospital_Boiler_1_Operation_Time": 12,
  "Hospital_Boiler_1_Gas_Consumption_Month": 1546,
  "Hospital_Boiler_1_Gas_Invoice_Month": 5565,
  "Hospital_Boiler_1_Gas_Cons_perentage": 43,
  "Hospital_Boiler_1_Gas_Invoice_percentage": 59,

  "Hospital_Boiler_2_Status": 0,            
  "Hospital_Boiler_2_Alarm": 1,           
  "Hospital_Boiler_2_Hot_Water_Volume": 978,
  "Hospital_Boiler_2_Hot_Water_Temperature": 0,
  "Hospital_Boiler_2_BC_Sequence_Time": 22537,
  "Hospital_Boiler_2_Operation_Time": 9,
  "Hospital_Boiler_2_Gas_Consumption_Month": 934,
  "Hospital_Boiler_2_Gas_Invoice_Month": 3362,
  "Hospital_Boiler_2_Gas_Cons_perentage": 39,
  "Hospital_Boiler_2_Gas_Invoice_percentage": 67,

  "Boiler_1_High_Gas_Pressure": 0,          
  "Boiler_2_High_Gas_Pressure": 0,          
  "Boiler_1_High_Oil_Pressure": 0,          
  "Boiler_2_High_Oil_Pressure": 1,          
  "Boiler_1_Low_Oil_Pressure": 0,           
  "Boiler_2_Low_Oil_Pressure": 0,           
  "Boiler_1_Air_Flow_Switch": 1,            
  "Boiler_2_Air_Flow_Switch": 1,            
  "Last_Operation_Boiler1": "24/8/2024",
  "Last_Operation_Boiler2": "25/8/2024",

  "Primary_Pump_1_Status": 1,               
  "Primary_Pump_2_Status": 1,               
  "Primary_Pump_3_Status": 0,               
  "Primary_Pump_Running_Count": 2,
  "Primary_Pump_Stopping_Count": 1,

  "Secondary_Pump_1_Status": 1,            
  "Secondary_Pump_2_Status": 0,            
  "Secondary_Pump_Running_Count": 1,
  "Secondary_Pump_Stopping_Count": 1,
  "in_Patients_GF": 220,
  "out_Patients_GF": 473,
  "monthlyenergy_Hospital_GF": 5860,
  "F_AHU_ON_GF": 9,              
  "F_AHU_OFF_GF": 8,             
  "monthly_carbon_foot_print_GF": 15, 
  "monthlycost_sg_GF": 5860,         
  "monthlyenergy_MVSG_GF": 8412,
  "Graph_Temperature_Boiler_1": {
    "Jan": 10,
    "Feb": 30,
    "Mar": 20,
    "Apr": 25,
    "May": 35,
    "Jun": 50,
    "Jul": 40,
    "Aug": 45,
    "Sep": 20,
    "Oct": 35,
    "Nov": 25,
    "Dec": 30
  },
  "Graph_Temperature_Boiler_2": {
    "Jan": 15,
    "Feb": 25,
    "Mar": 25,
    "Apr": 20,
    "May": 30,
    "Jun": 40,
    "Jul": 30,
    "Aug": 35,
    "Sep": 25,
    "Oct": 30,
    "Nov": 20,
    "Dec": 25
  },
  "Doctor_Present": 137,
  "Doctor_Absent": 89,
  "Nurse_Present": 235,
  "Nurse_Absent": 28,
  "Staff_Present": 341,
  "Staff_Absent": 32,
  "Residential_Beds_used": 63,
  // "Emergency_Beds_used": 75,
  "Intensive_Care_used": 42,
  "Neonatal_Intensive_used": 58,
  "surgery_appointments": [
    {
      "Patient_Name": "Ahmed Farouk",
      "Age": 42,
      "Gender": "Male",
      "Date_Time": "24.Jan 6:30pm",
      "Surgery": "Colonoscopy",
      "Surgeon": "Dr. Ayman"
    },
    {
      "Patient_Name": "Eyad Weal",
      "Age": 10,
      "Gender": "Child",
      "Date_Time": "24.Jan 12:00pm",
      "Surgery": "Adenoidectomy",
      "Surgeon": "Dr. Ahmed"
    },
    {
      "Patient_Name": "Hend Amr",
      "Age": 33,
      "Gender": "Female",
      "Date_Time": "24.Jan 3:00pm",
      "Surgery": "Laparose",
      "Surgeon": "Dr. Galal"
    },
    {
      "Patient_Name": "Sara El-Sayed",
      "Age": 28,
      "Gender": "Female",
      "Date_Time": "25.Jan 9:00am",
      "Surgery": "Appendectomy",
      "Surgeon": "Dr. Nader"
    },
    {
      "Patient_Name": "Omar Khaled",
      "Age": 35,
      "Gender": "Male",
      "Date_Time": "25.Jan 11:30am",
      "Surgery": "Gallbladder Removal",
      "Surgeon": "Dr. Samir"
    },
    {
      "Patient_Name": "Lina Mahmoud",
      "Age": 6,
      "Gender": "Child",
      "Date_Time": "25.Jan 2:00pm",
      "Surgery": "Tonsillectomy",
      "Surgeon": "Dr. Mona"
    },
    {
      "Patient_Name": "Mohamed Salem",
      "Age": 50,
      "Gender": "Male",
      "Date_Time": "26.Jan 8:00am",
      "Surgery": "Hernia Repair",
      "Surgeon": "Dr. Amr"
    },
    {
      "Patient_Name": "Fatma Ali",
      "Age": 62,
      "Gender": "Female",
      "Date_Time": "26.Jan 10:30am",
      "Surgery": "Knee Replacement",
      "Surgeon": "Dr. Hani"
    },
    {
      "Patient_Name": "Amal Ismail",
      "Age": 70,
      "Gender": "Female",
      "Date_Time": "26.Jan 3:30pm",
      "Surgery": "Cataract Surgery",
      "Surgeon": "Dr. Noor"
    }       
  ] ,
  "Cardiology": 105,
  "Neurology": 73,
  "Dermatology": 94 ,
  "carbon_foot_Clinics": 79,
  "carbon_foot_Hospital": 87,
  "carbon_foot_Utilites": 64,
  "Hospital_F_AHU_ON": 32,
  "Hospital_F_AHU_OFF": 14,
  "Hospital_GF_F_AHU_ON": 14,
  "Hospital_GF_F_AHU_OFF": 7,
  "dailyenergy_Hospital_GF": 1860,
  Surgeon_Efficiency:[
    {
        "surgeon": "Dr. Ayman",
        "team": "Team Alpha",
        "surgeries_performed": 12,
        "surgery_details": {
            "Colonoscopy": 5,
            "Appendectomy": 3,
            "Laparoscopy": 4
        }
    },
    {
        "surgeon": "Dr. Ahmed",
        "team": "Team Bravo",
        "surgeries_performed": 8,
        "surgery_details": {
            "Adenoidectomy": 3,
            "Colonoscopy": 2,
            "Appendectomy": 3
        }
    },
    {
        "surgeon": "Dr. Galal",
        "team": "Team Charlie",
        "surgeries_performed": 10,
        "surgery_details": {
            "Laparoscopy": 6,
            "Hernia Repair": 4
        }
    },
    {
        "surgeon": "Dr. Nader",
        "team": "Team Delta",
        "surgeries_performed": 15,
        "surgery_details": {
            "Knee Replacement": 5,
            "Appendectomy": 4,
            "Laparoscopy": 6
        }
    },
    {
        "surgeon": "Dr. Sara",
        "team": "Team Echo",
        "surgeries_performed": 7,
        "surgery_details": {
            "Colonoscopy": 3,
            "Gallbladder Surgery": 4
        }
    },
    {
        "surgeon": "Dr. Hassan",
        "team": "Team Foxtrot",
        "surgeries_performed": 9,
        "surgery_details": {
            "Hernia Repair": 5,
            "Knee Replacement": 4
        }
    }
] ,
"medical_gas_consumption": {
  "ground_floor": {
    "oxygen":2.4 ,
    "vacuum": -3.2 ,
    "air_7":6.5 ,
    "air_4":3.6 
  },
  "first_floor": {
    "oxygen":2.2 ,
    "vacuum": -3.0 ,
    "air_7":6.7 ,
    "air_4":3.8 
  },
  "second_floor": {
    "oxygen":2.6 ,
    "vacuum": -3.4 ,
    "air_7":6.8 ,
    "air_4":3.5 
  },
  "third_floor": {
    "oxygen":2.4 ,
    "vacuum": -3.2 ,
    "air_7":6.5 ,
    "air_4":3.6 
  }
}, 
  "Daily_staff_details": {
    "doctors": 137,
    "nurses": 235,
    "staffs": 469
  },
  "oxygen_consumption": {
    "consumption": 639,
    "invoice": 41390,
    "pressure": 4.2,
    "tank_1": 44,
    "tank_2": 56
  },
  "air_consumption": {
    "air_4_pressure": 3.7,
    "air_7_pressure": 6.8,
    "compressor_1_status": 1,
    "compressor_2_status": 0,
    "compressor_3_status": 1,
    "compressor_1_last_operation": "6/5/2024",
    "compressor_2_last_operation": "6/5/2024",
    "compressor_3_last_operation": "6/5/2024",
    "dryer_1_status": 1,
    "dryer_2_status": 0
  },
  "vacuum_consumption": {
    "current_pressure": "-6.6 bar",
      "pump_1": {
        "status": 1,
        "last_operation": "6/5/2024"
      },
      "pump_2": {
        "status": 1,
        "last_operation": "6/5/2024"
      },
      "pump_3": {
        "status": 0,
        "last_operation": "23/5/2024"
      }
  }
}